
all: project4

project4: project4.cpp
	g++ project4.cpp -o assign4 -I/usr/include/opencv -I/usr/include/opencv2 -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs

clean:
	rm assign4
