
all: project5

project4: project5.cpp
	g++ project5.cpp -o assign5 -I/usr/include/opencv -I/usr/include/opencv2 -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs

clean:
	rm assign5
